# Комментарии

## Создать комментарий
POST http://localhost:5000/comments/65298b47d6b7d2346689008d HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InR1Z2VyQG1haWwucnUiLCJuYW1lIjoiVGlnZXIgU2liYmVyIiwiaWQiOiI2NTQ2NmYwMmE1ZWFlMGM3N2NiNmQxMGMiLCJpYXQiOjE2OTkyMDMxNjYsImV4cCI6MTY5OTM3NTk2Nn0.eS9MPaCn4lQgJBhSycESXAUq8OGxSn5V35rh9jr8voU
Content-Type: application/json

{
  "_id": "ObjectId()",
  "text": "Проверка коментария после авторизации",
  "rating": "5",
  "offerId": "65298b47d6b7d2346689008d"
}

###
