# Комментарии

## Создать комментарий
POST http://localhost:5000/comments/65298ce10b5eed4a3deb9b92 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InR1Z2VyQG1haWwucnUiLCJuYW1lIjoiVGlnZXIgU2liYmVyIiwiaWQiOiI2NTQ2NmYwMmE1ZWFlMGM3N2NiNmQxMGMiLCJpYXQiOjE2OTk3MTY2MDQsImV4cCI6MTY5OTg4OTQwNH0.NUcYVkpr2o85Jxk6i6QFwxQ_7jnVi7yPhAKt6rcbDz4
Content-Type: application/json

{

  "text": "ПРОВЕРКА НОЧЬ СУББОТА",
  "rating": 1,
  "offerId": "65298ce10b5eed4a3deb9b92"
}

###
