## Добавить новое предложение
POST http://localhost:5000/offers HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImVub3QxMUBtYWlsLnJ1IiwibmFtZSI6IkVub3QxMSBTaWJiZXIiLCJpZCI6IjY1NGZhOGIwNjBjYWFjMmMzNGViMzRmZiIsImlhdCI6MTY5OTczMzE2NywiZXhwIjoxNjk5OTA1OTY3fQ.Hpcl5p9atFZedJ2WIjQUKeDlUYSYleT6Fr9IATZt9Vw
Content-Type: application/json

{
  "id": "67777794c57e98df0792177e",
  "title": "ПРОВЕРКА ПРЕМИАЛЬНЫХ БРЮССЕЛЬ ПРЕДЛОЖЕНИЙ",
  "description": "Discover the unique five-star Salute Inn hotel.",
  "postDate": "2023-11-06T09:50:49.728Z",
  "city": "brussels",
  "preview": "https://via.placeholder.com/260x200",
  "photos": [
    "https://via.placeholder.com/260x200?text=1",
    "https://via.placeholder.com/260x200?text=2",
    "https://via.placeholder.com/260x200?text=3",
    "https://via.placeholder.com/260x200?text=4",
    "https://via.placeholder.com/260x200?text=5",
    "https://via.placeholder.com/260x200?text=6"
  ],
  "premium": false,
  "favorite": true,
  "rating": 4,
  "houseType": "house",
  "roomNumber": 3,
  "guests": 1,
  "price": 100,
  "features": [
    "Air conditioning",
    "Laptop friendly workspace",
    "Washer"
  ],
  "userId": "67777794c57e98df0792177e",
  "commentCount": 10,
  "coords": {
    "latitude": 50.846557,
    "longitude": 4.351697
  }
}

###

## Изменит предложение
PATCH http://localhost:5000/offers/65787794c57e98df0792177e HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImVub3QxMUBtYWlsLnJ1IiwibmFtZSI6IkVub3QxMSBTaWJiZXIiLCJpZCI6IjY1NGZhOGIwNjBjYWFjMmMzNGViMzRmZiIsImlhdCI6MTY5OTczMzE2NywiZXhwIjoxNjk5OTA1OTY3fQ.Hpcl5p9atFZedJ2WIjQUKeDlUYSYleT6Fr9IATZt9Vw
Content-Type: application/json

{

  "premium": true

}

###


### Получить список премиальных предложений города
GET http://localhost:5000/offers/premium/Paris HTTP/1.1
Content-Type: application/json
