## Создать новое предложение

POST http://localhost:5000/offers HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImVub3QxMUBtYWlsLnJ1IiwibmFtZSI6IkVub3QxMSBTaWJiZXIiLCJpZCI6IjY1NGZhOGIwNjBjYWFjMmMzNGViMzRmZiIsImlhdCI6MTY5OTcyNTYzMiwiZXhwIjoxNjk5ODk4NDMyfQ.Z8lRa_aJ4ARvONuzhvLfezCd1uEsskpKV8txlYp37Rs
Content-Type: application/json

{
  "title": "проверка",
  "description": "Оффер после авторизации",
  "city": {},
  "preview": "https://via.placeholder.com/260x200",
  "photos": [
    "https://via.placeholder.com/260x200?text=1",
    "https://via.placeholder.com/260x200?text=2",
    "https://via.placeholder.com/260x200?text=3",
    "https://via.placeholder.com/260x200?text=4",
    "https://via.placeholder.com/260x200?text=5",
    "https://via.placeholder.com/260x200?text=6"
  ],
  "premium": true,
  "favorite": true,
  "rating": 4,
  "houseType": "house",
  "roomNumber": 5,
  "guests": 1,
  "price": 100,
  "features": [
    "Air conditioning",
    "Laptop friendly workspace",
    "Washer"
  ],
  //"user": {
  //  "mail": "tuger@mail.ru",
  //  "name": "Greg Greg",
  //  "avatar": "https://user.ru",
  //  "type": "pro"
  //},
  //"commentCount": 12,
  "coords": {},
  "postDate": "2023-10-13T17:54:05.378Z"
}

###


 # Получить объявление по идентификатору
GET http://localhost:5000/offers/65298b48d6b7d2346689009f HTTP/1.1

 ###


## Создать новое предложение

POST http://localhost:5000/offers HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImVub3QxMUBtYWlsLnJ1IiwibmFtZSI6IkVub3QxMSBTaWJiZXIiLCJpZCI6IjY1NGZhOGIwNjBjYWFjMmMzNGViMzRmZiIsImlhdCI6MTY5OTczNjUzMywiZXhwIjoxNjk5OTA5MzMzfQ.dQ2s0HdaYPK193DYLfn4yYfqFkR70jOThNHgD_qOfPc
Content-Type: application/json

{
  "title": "проверка",
  "description": "Оффер после авторизации",
  "city": "paris",
  "preview": "https://via.placeholder.com/260x200",
  "photos": [
    "https://via.placeholder.com/260x200?text=1",
    "https://via.placeholder.com/260x200?text=2",
    "https://via.placeholder.com/260x200?text=3",
    "https://via.placeholder.com/260x200?text=4",
    "https://via.placeholder.com/260x200?text=5",
    "https://via.placeholder.com/260x200?text=6"
  ],
  "premium": true,
  "favorite": true,
  "rating": 4,
  "houseType": "house",
  "roomNumber": 5,
  "guests": 1,
  "price": 1000,
  "features": [
    "Air conditioning",
    "Laptop friendly workspace",
    "Washer"
  ],
  "user": {
    "mail": "tuger@mail.ru",
    "name": "Greg Greg",
    "avatar": "https://user.ru",
    "type": "pro"
  },
  "commentCount": 7,
  "coords": {},
  "postDate": "2023-10-13T17:54:05.378Z"
}

###

 ## Создать новое предложение

POST http://localhost:5000/offers HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImVub3QxMUBtYWlsLnJ1IiwibmFtZSI6IkVub3QxMSBTaWJiZXIiLCJpZCI6IjY1NGZhOGIwNjBjYWFjMmMzNGViMzRmZiIsImlhdCI6MTY5OTczNjUzMywiZXhwIjoxNjk5OTA5MzMzfQ.dQ2s0HdaYPK193DYLfn4yYfqFkR70jOThNHgD_qOfPc
Content-Type: application/json

{
 
  "title": "проверка авторизации",
  "description": "Оффер после авторизации",
  "city": "Paris",
  "preview": "https://via.placeholder.com/260x200",
  "photos": [
    "https://via.placeholder.com/260x200?text=1",
    "https://via.placeholder.com/260x200?text=2",
    "https://via.placeholder.com/260x200?text=3",
    "https://via.placeholder.com/260x200?text=4",
    "https://via.placeholder.com/260x200?text=5",
    "https://via.placeholder.com/260x200?text=6"
  ],
  "premium": true,
  "favorite": true,
  "rating": 4,
  "houseType": "house",
  "roomNumber": 5,
  "guests": 1,
  "price": 1500,
  "features": [
    "Air conditioning",
    "Laptop friendly workspace",
    "Washer"
  ],
  //"userId": "65466f02a5eae0c77cb6d10c",
  "user": {
    "email": "tuger@mail.ru",
    "name": "Tiger Sibber",
    "avatar": "https://user.ru",
    "type": "pro"
  },

  "commentCount": 10,
  "coords": {
     "latitude": 48.85661,
        "longitude": 2.351499,
        "_id": "65298b48d6b7d2346689009b"
  },
  "postDate": "2023-10-13T17:54:05.378Z"
}


###




 ## Удалить объявление по идентификатору

DELETE http://localhost:5000/offers/6528507c43cdb112248edb68 HTTP/1.1

 ###

 








