
 # Получить объявление по идентификатору
GET http://localhost:5000/offers/65298b48d6b7d2346689009f HTTP/1.1

 ###


 ## Создать новое предложение

POST http://localhost:5000/offers HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InR1Z2VyQG1haWwucnUiLCJuYW1lIjoiVGlnZXIgU2liYmVyIiwiaWQiOiI2NTQ2NmYwMmE1ZWFlMGM3N2NiNmQxMGMiLCJpYXQiOjE2OTkxMTU4MDgsImV4cCI6MTY5OTI4ODYwOH0.mrRvrZpfFQ_jRLvM1T5qsf9MHMnUxe9mXPIgxDpkY-w
Content-Type: application/json

{
  "title": "5",
  "description": "Оффер после авторизации",
  "city": {},
  "preview": "https://via.placeholder.com/260x200",
  "photos": [
    "https://via.placeholder.com/260x200?text=1",
    "https://via.placeholder.com/260x200?text=2",
    "https://via.placeholder.com/260x200?text=3",
    "https://via.placeholder.com/260x200?text=4",
    "https://via.placeholder.com/260x200?text=5",
    "https://via.placeholder.com/260x200?text=6"
  ],
  "premium": true,
  "favorite": true,
  "rating": 4,
  "houseType": "house",
  "roomNumber": 5,
  "guests": 1,
  "price": 1000,
  "features": [
    "Air conditioning",
    "Laptop friendly workspace",
    "Washer"
  ],
  "user": {
    "mail": "tuger@mail.ru",
    "name": "Greg Greg",
    "avatar": "https://user.ru",
    "type": "pro"
  },
  "commentCount": 12,
  "coords": {},
  "postDate": "2023-10-13T17:54:05.378Z"
}


###


 ## Удалить объявление по идентификатору

DELETE http://localhost:5000/offers/6528507c43cdb112248edb68 HTTP/1.1

 ###





